language: python
dist: xenial
os: linux

jobs:
  include:
    - python: '3.7'
      name: "flake8"
      env: TOXENV="flake8"

    - python: '2.7'
      env:
        - SO_S3_URL: "s3://smart-open-py27-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py27-benchmark-results"
        - BOTO_CONFIG: "/dev/null"
        - TOXENV: "check_keys,py27-test,py27-benchmark,py27-integration"

    - python: '3.5'
      env: TOXENV="check_keys,py35-test,py35-integration"

    - python: '3.6'
      env:
        - SO_S3_URL: "s3://smart-open-py36-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py36-benchmark-results"
        - BOTO_CONFIG: "/dev/null"
        - TOXENV: "check_keys,py36-doctest,py36-test,py36-benchmark,py36-integration"

    - python: '3.7'
      env:
        - SO_S3_URL: "s3://smart-open-py37-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py37-benchmark-results"
        - BOTO_CONFIG: "/dev/null"
        - SO_ENABLE_MOTO_SERVER: "1"
        - TOXENV: "check_keys,py37-doctest,enable_moto_server,py37-test,py37-benchmark,py37-integration,disable_moto_server"

install:
  - pip install tox

script: tox -vv

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
